# The Docker image that will be used to build your app
image: archlinux:base-devel-20230305.0.131236
# Functions that should be executed before the build script is run
before_script:
  - pacman -Sy wget ruby git --noconfirm
  - gem install jekyll bundler
pages:
  script:
    - export PATH=$PATH:/root/.local/share/gem/ruby/3.0.0/bin
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public

  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
