title: FakeNarratives
email: "fakenarratives@l3s.de"
description: Understanding Narratives of Disinformation in Public and Alternative News Videos
author: "FakeNarratives"
baseurl: ""
url: "https://fakenarratives.github.io"

# Social Profiles
# twitter_username: SBootstrap
github_username: fakenarratives
# facebook_username: StartBootstrap
# instagram_username:
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-gist
  - jekyll-scholar

# Bibliography
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  group_by: type, year
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
